# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that builds Maven-based applications from source"
  homepage = "https://github.com/paketo-buildpacks/maven"
  id = "paketo-buildpacks/maven"
  keywords = ["java", "maven", "build-system"]
  name = "Paketo Maven Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "6.7.0"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/maven/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "-Dmaven.test.skip=true --no-transfer-progress package"
    description = "the arguments to pass to Maven"
    name = "BP_MAVEN_BUILD_ARGUMENTS"

  [[metadata.configurations]]
    build = true
    default = "target/*.[ejw]ar"
    description = "the built application artifact explicitly.  Supersedes $BP_MAVEN_BUILT_MODULE"
    name = "BP_MAVEN_BUILT_ARTIFACT"

  [[metadata.configurations]]
    build = true
    default = "pom.xml"
    description = "the location of the main pom.xml file, relative to the application root"
    detect = true
    name = "BP_MAVEN_POM_FILE"

  [[metadata.configurations]]
    build = true
    description = "the module to find application artifact in"
    name = "BP_MAVEN_BUILT_MODULE"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "use maven daemon"
    name = "BP_MAVEN_DAEMON_ENABLED"

  [[metadata.configurations]]
    build = true
    description = "the path to a Maven settings file"
    name = "BP_MAVEN_SETTINGS_PATH"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:maven:3.8.6:*:*:*:*:*:*:*"]
    id = "maven"
    name = "Apache Maven"
    purl = "pkg:generic/apache-maven@3.8.6"
    sha256 = "c7047a48deb626abf26f71ab3643d296db9b1e67f1faa7d988637deac876b5a9"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.tar.gz"
    version = "3.8.6"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:mvnd:0.8.0:*:*:*:*:*:*:*"]
    id = "mvnd"
    name = "Apache Maven Daemon"
    purl = "pkg:generic/apache-mvnd@0.8.0"
    sha256 = "ab959b606455e0576c5cf39d5f8252f5d2b4d67978a84cd669720f1c2d18fb73"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://github.com/apache/maven-mvnd/releases/download/0.8.0/maven-mvnd-0.8.0-linux-amd64.zip"
    version = "0.8.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
