api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-module-bom"
  id = "paketo-buildpacks/node-module-bom"
  name = "Paketo Buildpack for Node Module Bill of Materials Generator"
  version = "0.4.3"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/node-module-bom/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:owasp:cyclonedx-node-module:3.10.4:*:*:*:*:*:*:*"
    id = "cyclonedx-node-module"
    licenses = ["Apache-2.0", "ECL-2.0", "SHL-0.51", "SHL-0.5"]
    name = "CycloneDX Node.js Module"
    purl = "pkg:npm/%40cyclonedx/bom@3.10.4"
    sha256 = "45f60fc7c8b048d07a43bb9c261d298bf6fd74b52ed1b55c42255be5a0dc91b9"
    source = "https://registry.npmjs.org/@cyclonedx/bom/-/bom-3.10.4.tgz"
    source_sha256 = "7312b6d8d248d75da08a7d283833495fc7ede8ea6b6a1a38fc4aa6cdeb95125e"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/cyclonedx-node-module/cyclonedx-node-module_3.10.4_linux_x64_bionic_45f60fc7.tgz"
    version = "3.10.4"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "cyclonedx-node-module"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
