# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  id       = "paketo-buildpacks/dist-zip"
  name     = "Paketo DistZip Buildpack"
  version  = "5.3.0"
  homepage = "https://github.com/paketo-buildpacks/dist-zip"
  description = "A Cloud Native Buildpack that contributes a Process Type for DistZip-style applications"
  keywords    = ["java", "dist-zip"]
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-buildpacks/dist-zip/blob/main/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "*"

[[metadata.configurations]]
name        = "BP_APPLICATION_SCRIPT"
description = "the application start script"
default     = "*/bin/*"
build       = true

[[metadata.configurations]]
name        = "BP_LIVE_RELOAD_ENABLED"
description = "enable live process reload in the image"
default     = "false"
build       = true

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
