# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes Spring Boot dependency information and slices an application into multiple layers"
  homepage = "https://github.com/paketo-buildpacks/spring-boot"
  id = "paketo-buildpacks/spring-boot"
  keywords = ["java", "spring", "spring-boot"]
  name = "Paketo Spring Boot Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "5.8.0"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/spring-boot/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml", "spring-generations.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "true"
    description = "whether to contribute Spring Boot cloud bindings support"
    name = "BP_SPRING_CLOUD_BINDINGS_ENABLED"

  [[metadata.configurations]]
    default = "true"
    description = "Deprecated - whether to auto-configure Spring Boot environment properties from bindings"
    launch = true
    name = "BPL_SPRING_CLOUD_BINDINGS_ENABLED"

  [[metadata.configurations]]
    default = "false"
    description = "whether to auto-configure Spring Boot environment properties from bindings"
    launch = true
    name = "BPL_SPRING_CLOUD_BINDINGS_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:vmware:spring_cloud_bindings:1.8.1:*:*:*:*:*:*:*"]
    id = "spring-cloud-bindings"
    name = "Spring Cloud Bindings"
    purl = "pkg:generic/springframework/spring-cloud-bindings@1.8.1"
    sha256 = "a4640d93b0ed6664c62d7f5c7aab2ad364bfe5881acb0acfe8742e5e03369873"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.8.1/spring-cloud-bindings-1.8.1.jar"
    version = "1.8.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/spring-cloud/spring-cloud-bindings/blob/main/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
