# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes Apache Tomcat and Process Types for WARs"
  homepage = "https://github.com/paketo-buildpacks/apache-tomcat"
  id = "paketo-buildpacks/apache-tomcat"
  keywords = ["java", "tomcat", "war"]
  name = "Paketo Apache Tomcat Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "7.5.0"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/apache-tomcat/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml", "resources/context.xml", "resources/logging.properties", "resources/server.xml", "resources/web.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    description = "the Tomcat access logging state"
    launch = true
    name = "BPL_TOMCAT_ACCESS_LOGGING_ENABLED"

  [[metadata.configurations]]
    build = true
    description = "the application context path"
    name = "BP_TOMCAT_CONTEXT_PATH"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable Tomcat's EnvironmentPropertySource"
    name = "BP_TOMCAT_ENV_PROPERTY_SOURCE_DISABLED"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the external Tomcat configuration archive"
    name = "BP_TOMCAT_EXT_CONF_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the external Tomcat configuration archive"
    name = "BP_TOMCAT_EXT_CONF_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the external Tomcat configuration"
    name = "BP_TOMCAT_EXT_CONF_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the external Tomcat configuration"
    name = "BP_TOMCAT_EXT_CONF_VERSION"

  [[metadata.configurations]]
    build = true
    default = "9.*"
    description = "the Tomcat version"
    name = "BP_TOMCAT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:tomcat:8.5.82:*:*:*:*:*:*:*"]
    id = "tomcat"
    name = "Apache Tomcat"
    purl = "pkg:generic/apache-tomcat@8.5.82"
    sha256 = "33098049ff0154a68313a0e5974c88e99b945e42a8b661c190f1dba401e2b5b3"
    stacks = ["*"]
    uri = "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz"
    version = "8.5.82"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:tomcat:9.0.65:*:*:*:*:*:*:*"]
    id = "tomcat"
    name = "Apache Tomcat"
    purl = "pkg:generic/apache-tomcat@9.0.65"
    sha256 = "e92330e6b0103eb0a5af1ec42f8c0aaaf0da712b7449b962e181a191e8f2264b"
    stacks = ["*"]
    uri = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz"
    version = "9.0.65"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:apache:tomcat:10.0.23:*:*:*:*:*:*:*"]
    id = "tomcat"
    name = "Apache Tomcat"
    purl = "pkg:generic/apache-tomcat@10.0.23"
    sha256 = "575c99a2aeed61e26b2f379bd0f8c9e44a4ecc9509760aa81c20bb7126b7fd3d"
    stacks = ["*"]
    uri = "https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz"
    version = "10.0.23"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://www.apache.org/licenses/"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:cloudfoundry:tomcat-access-logging-support:3.3.0:*:*:*:*:*:*:*"]
    id = "tomcat-access-logging-support"
    name = "Apache Tomcat Access Logging Support"
    purl = "pkg:generic/tomcat-access-logging-support@3.3.0"
    sha256 = "49f9acac1bed65c683276d662c985ed63c685a603e7f5b72f732673bb826a0d4"
    stacks = ["*"]
    uri = "https://repo.spring.io/release/org/cloudfoundry/tomcat-access-logging-support/3.3.0.RELEASE/tomcat-access-logging-support-3.3.0.RELEASE.jar"
    version = "3.3.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/cloudfoundry/java-buildpack-support/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:cloudfoundry:tomcat-lifecycle-support:3.3.0:*:*:*:*:*:*:*"]
    id = "tomcat-lifecycle-support"
    name = "Apache Tomcat Lifecycle Support"
    purl = "pkg:generic/tomcat-lifecycle-support@3.3.0"
    sha256 = "b725f4cae0be4a999a08ed978b29081edfd68a187a926ed740cc1f8e9aca70ce"
    stacks = ["*"]
    uri = "https://repo.spring.io/release/org/cloudfoundry/tomcat-lifecycle-support/3.3.0.RELEASE/tomcat-lifecycle-support-3.3.0.RELEASE.jar"
    version = "3.3.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/cloudfoundry/java-buildpack-support/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:cloudfoundry:tomcat-logging-support:3.3.0:*:*:*:*:*:*:*"]
    id = "tomcat-logging-support"
    name = "Apache Tomcat Logging Support"
    purl = "pkg:generic/tomcat-logging-support@3.3.0"
    sha256 = "46db58c1d8ef2555d7053a12d669daefb676e9a17a2a1771cd60c95bcb210b0d"
    stacks = ["*"]
    uri = "https://repo.spring.io/release/org/cloudfoundry/tomcat-logging-support/3.3.0.RELEASE/tomcat-logging-support-3.3.0.RELEASE.jar"
    version = "3.3.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/cloudfoundry/java-buildpack-support/blob/main/LICENSE"

[[stacks]]
  id = "*"
