api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-run-script"
  id = "paketo-buildpacks/node-run-script"
  name = "Paketo Buildpack for Node Run Script"
  version = "0.5.1"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/node-run-script/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
